# -*- coding: utf-8 -*-
"""python-practice-Day1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A8HN7FYzl_uIU_yTNxX8J0UtIGNwEw1u
"""

import pandas as pd
from tabulate  import tabulate  #used to tabulate the data
import traceback  #used for error handling and debugging with detailed error details
import numpy as np
import matplotlib.pyplot as plt  #used for visualizing the data in the format of bars,plots...
from requests import get  #used to interact with web services by sending the HTTP link to it
import requests
import os #used to interact with os and file handling such as file manipulation,environment variable,directory list

"""### **LIST**"""

empty_list=[]
city_list=["Bangalore","Chennai","Mumbai","Pune"]
print(city_list)
city_list.append("THANE")  #the element is added at the end of list
print(city_list)
age_list=[10,20]
print(age_list)
age_list.append(100)
print(age_list)
multiple_data_list=[10,"Riya",{1:"One"},[100,200],(1,2,3)]
print(multiple_data_list)

"""## **FUNCTIONS IN LIST**"""

count_age=age_list.count(10)
print("Count: ",count_age)

age_list.extend(["vishnu","riya"])   #used to add multiple elements at a time
print("Extended list :" ,age_list)

a=city_list.index('Chennai')
print("Index of data : ",a)

for val in city_list:
  print(val)

print("                 Accessing values by index :    ")
for val in range(len(city_list)):
  print(city_list[val])


print("                 Accessing values along index :    ")
for i,value in enumerate(city_list):
  print(f"The value at index {i} is {value}")

print("\n                  Accessing by single word         ")
for i in range(len(city_list)):
  if city_list[i] == "Bangalore":

    for word in city_list[i]:
      print(word)



print("******check if value is exist*******")
if "Chennai" in city_list:
  print("yes")
else:
  print("no")

"""# **DICTIONARY**"""

dict_data={}
print(dict_data)


dict_data['pet']=[]
print(dict_data)


dict_data['pet'].append({
'name': 'Dog',
'website': 'dog.com',
'from': 'San Francisco'
})
dict_data['pet'].append({
'name': 'Cat',
'website': 'hellokitty.com',
'from': 'Seattle'
})
dict_data['pet'].append({
'name':'Parrot',
'age':2,
'website':'parrotworld.com',
'from':'Ireland'
})
print(dict_data)


print("\n   ******Accessing single value************")
for value in dict_data['pet']:
  for i in value.items():
    print("Values of keys are : ",list(i)[1])


print("\n single values : ",dict_data['pet'][0])
print("\n length of dictionary : ",len(dict_data['pet']))  #it retruns the whole length of dictionary

dict_pets={"pets":[{'name':'dog','age':2},{'name':'dog','age':2}]}
dict_p_h={"pets": [{"name": "dog", "age": 2}, {"name": "dog", "age":2}],
"persons": [{"name": "ram", "age": 12}, {"name": "kumaran","age": 11}]}
print(dict_p_h["pets"][0].values())
c_pets, c_humans = len(dict_pets), len(dict_p_h)
print("Length of pets and humans : ",c_pets, c_humans)


keys_lst=[*dict_p_h]
print("\n Keys of dict : ",keys_lst)

values_lst=[*dict_p_h.values()]
print("\n Values of dict : ",values_lst)

